version: 2

sources:
  - name: gz_raw_data
    description: greenweez raw data source
    tables:
    - name: raw_gz_product
      description : product
      columns:
      - name: products_id
        description : "primary key of the table"
        tests: 
            - unique
            - not_null
    
    - name: raw_gz_sales
      description : sales
      columns:
        - name: orders_id
          description: primary key of the table
          tests: 
              - unique
              - not_null
    - name: raw_gz_ship
      description : ship
      columns:
        - name: orders_id
          description: primary key of the table
          tests: 
            - unique
            - not_null